{% set name = "humre" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Humre-{{ version }}.tar.gz
  sha256: cee7835c586eef58d04233410547b8114abb025a771eee6b71afdea0ba87924a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - humre
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/asweigart/humre
  summary: A human-readable regular expression module for Python. Humre handles regex syntax for you and creates regex strings to pass to Python's re.compile(). Pronounced "hum, ree".
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
